export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CHECKLIST_NOT_FOUND: "CHECKLIST_NOT_FOUND",
  CHECKLIST_NOT_PUBLISHED: "CHECKLIST_NOT_PUBLISHED",
  CHECKLIST_ALREADY_PUBLISHED: "CHECKLIST_ALREADY_PUBLISHED",
  CHECKLIST_VERSION_CONFLICT: "CHECKLIST_VERSION_CONFLICT",
  CHECKLIST_ITEM_NOT_FOUND: "CHECKLIST_ITEM_NOT_FOUND",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_ALREADY_SUBMITTED: "TASK_ALREADY_SUBMITTED"
} as const;
