export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  CHECKLIST_NOT_FOUND: "CHECKLIST_NOT_FOUND",
  CHECKLIST_NOT_PUBLISHABLE: "CHECKLIST_NOT_PUBLISHABLE",
  CHECKLIST_NO_PUBLISHED_VERSION: "CHECKLIST_NO_PUBLISHED_VERSION",
  CHECKLIST_ITEM_CODE_CONFLICT: "CHECKLIST_ITEM_CODE_CONFLICT",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_NOT_SUBMITTABLE: "TASK_NOT_SUBMITTABLE",
  TASK_CHECKLIST_VERSION_MISSING: "TASK_CHECKLIST_VERSION_MISSING",
  RESULT_ITEM_UNKNOWN: "RESULT_ITEM_UNKNOWN",
  HAZARD_NOT_FOUND: "HAZARD_NOT_FOUND",
  HAZARD_ALREADY_CLOSED: "HAZARD_ALREADY_CLOSED"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
