# 巡检清单生命周期状态。
# DRAFT     草稿：物业编辑中，未发布，不能被任务引用
# PUBLISHED 已发布：建任务时唯一可固定的版本
# ARCHIVED  已归档：曾被发布、现被新版本取代（历史任务仍固定引用它）
CHECKLIST_STATUS_DRAFT = "DRAFT"
CHECKLIST_PUBLISHED = "PUBLISHED"
CHECKLIST_ARCHIVED = "ARCHIVED"

CHECKLIST_STATUS = (
    CHECKLIST_STATUS_DRAFT,
    CHECKLIST_PUBLISHED,
    CHECKLIST_ARCHIVED,
)
