# 错误码集中维护；service / controller 既通过 ERROR_CODES 取值，
# 也直接按名导入，新增错误码时必须同步 error_messages 与各调用处。
AUTH_REQUIRED = "AUTH_REQUIRED"
RBAC_DENIED = "RBAC_DENIED"
VALIDATION_FAILED = "VALIDATION_FAILED"

# 清单版本化相关错误码
CHECKLIST_NOT_FOUND = "CHECKLIST_NOT_FOUND"
CHECKLIST_NOT_PUBLISHABLE = "CHECKLIST_NOT_PUBLISHABLE"
CHECKLIST_NO_PUBLISHED_VERSION = "CHECKLIST_NO_PUBLISHED_VERSION"
CHECKLIST_ITEM_CODE_CONFLICT = "CHECKLIST_ITEM_CODE_CONFLICT"

# 任务提交相关错误码
TASK_NOT_FOUND = "TASK_NOT_FOUND"
TASK_NOT_SUBMITTABLE = "TASK_NOT_SUBMITTABLE"
TASK_CHECKLIST_VERSION_MISSING = "TASK_CHECKLIST_VERSION_MISSING"
RESULT_ITEM_UNKNOWN = "RESULT_ITEM_UNKNOWN"

# 隐患合并相关错误码
HAZARD_NOT_FOUND = "HAZARD_NOT_FOUND"
HAZARD_ALREADY_CLOSED = "HAZARD_ALREADY_CLOSED"

ERROR_CODES = {
    "AUTH_REQUIRED": AUTH_REQUIRED,
    "RBAC_DENIED": RBAC_DENIED,
    "VALIDATION_FAILED": VALIDATION_FAILED,
    "CHECKLIST_NOT_FOUND": CHECKLIST_NOT_FOUND,
    "CHECKLIST_NOT_PUBLISHABLE": CHECKLIST_NOT_PUBLISHABLE,
    "CHECKLIST_NO_PUBLISHED_VERSION": CHECKLIST_NO_PUBLISHED_VERSION,
    "CHECKLIST_ITEM_CODE_CONFLICT": CHECKLIST_ITEM_CODE_CONFLICT,
    "TASK_NOT_FOUND": TASK_NOT_FOUND,
    "TASK_NOT_SUBMITTABLE": TASK_NOT_SUBMITTABLE,
    "TASK_CHECKLIST_VERSION_MISSING": TASK_CHECKLIST_VERSION_MISSING,
    "RESULT_ITEM_UNKNOWN": RESULT_ITEM_UNKNOWN,
    "HAZARD_NOT_FOUND": HAZARD_NOT_FOUND,
    "HAZARD_ALREADY_CLOSED": HAZARD_ALREADY_CLOSED,
}
