# 隐患整改单状态。只有非 CLOSED 的单据才参与“同设备未关闭隐患合并”。
HAZARD_STATUS_OPEN = "OPEN"
HAZARD_STATUS_RECTIFYING = "RECTIFYING"
HAZARD_STATUS_REVIEWING = "REVIEWING"
HAZARD_CLOSED = "CLOSED"

HAZARD_RECTIFY_STATUS = (
    HAZARD_STATUS_OPEN,
    HAZARD_STATUS_RECTIFYING,
    HAZARD_STATUS_REVIEWING,
    HAZARD_CLOSED,
)

# 合并判定：这些状态视为“未关闭”，同设备再次发现异常时累计发现次数而不是新建单据
HAZARD_OPEN_STATUSES = (
    HAZARD_STATUS_OPEN,
    HAZARD_STATUS_RECTIFYING,
    HAZARD_STATUS_REVIEWING,
)
