InspectionStatus = ["PLANNED","IN_PROGRESS","SUBMITTED","REVIEWED","OVERDUE"]

# 任务状态语义常量（供 service/controller/日志共用）
TASK_STATUS_PLANNED = "PLANNED"
TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
TASK_STATUS_SUBMITTED = "SUBMITTED"
TASK_STATUS_REVIEWED = "REVIEWED"
TASK_STATUS_OVERDUE = "OVERDUE"

# 允许提交判级的任务状态：已领取（执行中）与已排期均可提交
TASK_SUBMITTABLE_STATUSES = (TASK_STATUS_PLANNED, TASK_STATUS_IN_PROGRESS)
